### ISSUE TITLE
About the visualization code in Segformer paper

### ISSUE THREAD

**Issue by VoyageWang** [iumyx2612/mmsegmentation#2]
Hi, I noticed that you looked for the effective receptive field visualization code in the Segformer paper. Have you already solved this? If yes, can you share the code with me? It will help me a lot.

**Comment by iumyx2612** [comment]
> Hi, I noticed that you looked for the effective receptive field visualization code in the Segformer paper. Have you already solved this? If yes, can you share the code with me? It will help me a lot.

Hi, I found out how to visualize ERF, pytorch code is taken from RepLKNet repo: https://github.com/DingXiaoH/RepLKNet-pytorch

**Comment by VoyageWang** [comment]
你好，你的邮件已经被我接受。hello，your email has been recieved. Thank you.
